"""Built-in operation order.

What: the order the catalog had before each operation moved into its own file.
Where: app/modules/order.py. The catalog sorts with sort_key.
Why: a new module appends its operations. Built-in ids stay where API clients already saw them.
"""

from __future__ import annotations

# Generated by the module split. Built-in catalog order.
CATALOG_ORDER = (
    "internal.health",
    "console.release",
    "console.backup",
    "console.vacuum",
    "host.preflight",
    "host.basic_ops",
    "genestack.components.desired",
    "genestack.service.enable",
    "genestack.scripts.list",
    "genestack.repo_scripts.list",
    "genestack.repo_script.run",
    "genestack.smoke",
    "genestack.components.list",
    "genestack.components.reconcile",
    "genestack.services.list",
    "genestack.cluster.status",
    "genestack.pipeline.run",
    "ansible.playbook.run",
    "genestack.config.push",
    "genestack.state.export",
    "genestack.verify",
    "genestack.tempest",
    "genestack.talos.bootstrap",
    "genestack.k8s_upgrade",
    "genestack.hyperconverged_lab",
    "genestack.backup_mariadb",
    "genestack.deploy",
    "genestack.greenfield",
    "registry.mirror",
    "genestack.host_prepare",
    "genestack.host_setup",
    "openstack.servers.list",
    "openstack.server.start",
    "openstack.server.stop",
    "openstack.server.reboot",
    "openstack.server.delete",
    "baremetal.node.register",
    "baremetal.nodes.list",
    "baremetal.node.power",
    "baremetal.node.pxe_boot",
    "baremetal.node.next_boot",
    "baremetal.node.iso_boot",
    "baremetal.node.provision",
    "baremetal.bmc_scan",
    "hardware.terraform.plan",
    "hardware.terraform.apply",
    "hostvm.list",
    "hostvm.start",
    "hostvm.stop",
    "hostvm.restart",
    "agent.status",
    "agent.command",
    "agent.install",
    "ovh.byoi.reinstall",
    "ovh.vrack.attach",
    "platform.talos.reboot",
    "platform.talos.shutdown",
    "platform.talos.reset",
    "platform.talos.upgrade",
    "platform.talos.upgrade_many",
    "platform.talos.apply_config",
    "k8s.node.drain",
    "k8s.apply",
    "app.deploy",
    "hosts.ubuntu.prepare",
    "hosts.microk8s.install",
    "hosts.kubespray.adopt",
)


def sort_key(operation_id: str) -> tuple[int, str]:
    """Known ids keep their old place. Anything else sorts after them."""
    try:
        return (CATALOG_ORDER.index(operation_id), "")
    except ValueError:
        return (len(CATALOG_ORDER), operation_id)

